// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {CommitmentStatus} from "./storage.sol";

error AlreadyClaimed();
error AlreadyJoined();
error CannotCancelAfterOthersHaveJoined();
error CommitmentDoesNotExist();
error CommitmentNotActive();
error CommitmentNotCancelled();
error CommitmentNotExists(uint256 id);
error CommitmentNotResolved();
error DescriptionTooLong();
error DisperseCallFailed();
error DuplicateWinner(address winner);
error FulfillmentPeriodNotEnded(uint256 currentTime, uint256 deadline);
error InvalidCreationFee(uint256 sent, uint256 required);
error InvalidCreationFeeNative();
error InvalidFullfillmentDeadline();
error InvalidJoinDeadline();
error InvalidJoinFee(uint256 sent, uint256 required);
error InvalidJoinFeeNative();
error InvalidFundingAmount();
error InvalidNumberOfWinners();
error InvalidStakeAmount();
error InvalidStakeAmountNative();
error InvalidState(CommitmentStatus status);
error InvalidTokenId();
error InvalidWinner(address winner);
error InvalidWinnerAddress();
error JoinDealineTooEarly();
error JoiningPeriodEnded(uint256 currentTime, uint256 deadline);
error NoCreatorFeesToClaim();
error NoRewardsToClaim();
error NotAParticipant();
error OnlyCreatorCanClaim();
error OnlyCreatorCanResolve();
error OnlyCreatorOrOwnerCanCancel();
error OnlyCreatorOrOwnerCanUpdateURI();
error TokenNotAllowed(address token);
